/*
 *  Perutax - Taxation software for Peru.
 *     Copyright (C) 2021-2022  Ingenieria Informatica Yupay SACS
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.yupay.perutax.entities;

import jakarta.persistence.*;
import javafx.beans.property.*;

import java.math.BigDecimal;

/**
 * This entity represents one line shown in the folio.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
@Entity
@Table(name = "folio_line", schema = "public")
public class FolioLine {
    /**
     * Autogenerated ID.
     */
    private final LongProperty id =
            new SimpleLongProperty(this, "id");
    /**
     * Line number (order of appareance in printed folio).
     */
    private final IntegerProperty line =
            new SimpleIntegerProperty(this, "line");
    /**
     * Taxable amount.
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> taxableFc =
            new SimpleObjectProperty<>(this, "taxableFc");
    /**
     * Tax amount.
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> taxFc =
            new SimpleObjectProperty<>(this, "taxFc");
    /**
     * Exportation amount.
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> exportFc =
            new SimpleObjectProperty<>(this, "exportFc");
    /**
     * Discount amount (price portion).
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> discountFc =
            new SimpleObjectProperty<>(this, "discountFc");
    /**
     * Discount amount (tax portion).
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> discountTaxFc =
            new SimpleObjectProperty<>(this, "discountTaxFc");
    /**
     * Tax exempt amount.
     * Expressed in folio currency.
     *
     * @implNote The difference between a tax free
     * item and exempt amount, is that the tax free
     * item is an item not included in the taxation law
     * as a taxable amount; while an exempt amount is
     * the one that is included in law as a taxable item
     * but for some sepcial reason, has been
     * temporarily exempted from paying the tax.
     */
    private final ObjectProperty<BigDecimal> exemptFc =
            new SimpleObjectProperty<>(this, "exemptFc");
    /**
     * Free of tax amount.
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> taxFreeFc =
            new SimpleObjectProperty<>(this, "taxFreeFc");
    /**
     * Plastic bags (ICBP) tax amount.
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> icbpFc =
            new SimpleObjectProperty<>(this, "icbpFc");
    /**
     * Others amounts.
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> othersFc =
            new SimpleObjectProperty<>(this, "othersFc");
    /**
     * Payable amount (sum of all other amounts).
     * Expressed in folio currency.
     */
    private final ObjectProperty<BigDecimal> payableFc =
            new SimpleObjectProperty<>(this, "payableFc");
    /**
     * The briefing (description) of item text.
     * The briefing shouldn't include details of
     * the item, those details (Color, size, presentation,
     * serial numbers, product numbers, etc) should be
     * stated in a dimension (there're 4 spaces for dimensions).
     */
    private final StringProperty briefing =
            new SimpleStringProperty(this, "briefing");
    /**
     * Description of item, 1st dimension.
     */
    private final StringProperty dim1 =
            new SimpleStringProperty(this, "dim1");
    /**
     * Description of item, 2nd dimension.
     */
    private final StringProperty dim2 =
            new SimpleStringProperty(this, "dim2");
    /**
     * Description of item, 3rd dimension.
     */
    private final StringProperty dim3 =
            new SimpleStringProperty(this, "dim3");
    /**
     * Description of item, 4th dimension.
     */
    private final StringProperty dim4 =
            new SimpleStringProperty(this, "dim4");
    /**
     * The tax ID. In Peru a folio line
     * in a sale operation should contain
     * an 8-digits ID of the item as assigned
     * by UN standards.
     */
    private final StringProperty taxId =
            new SimpleStringProperty(this, "taxId");
    /**
     * The folio to where this line belongs.
     */
    private final ObjectProperty<Folio> owner =
            new SimpleObjectProperty<>(this, "owner");

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #id}
     */
    @GeneratedValue(generator = "folioline_id")
    @SequenceGenerator(name = "folioline_id",
            schema = "public",
            sequenceName = "sq_folio_line_id",
            allocationSize = 1)
    @Id
    @Column(name = "id")
    public long getId() {
        return id.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param id the value to set into {@link #id}
     */
    public void setId(long id) {
        this.id.set(id);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #line }
     */
    @Basic
    @Column(name = "line")
    public short getLine() {
        return (short) line.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param line the value to set into {@link #line}
     */
    public void setLine(short line) {
        this.line.set(line);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxableFc }
     */
    @Basic
    @Column(name = "taxable_fc", scale = 2, precision = 14)
    public BigDecimal getTaxableFc() {
        return taxableFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxableFc the value to set into {@link #taxableFc}
     */
    public void setTaxableFc(BigDecimal taxableFc) {
        this.taxableFc.set(taxableFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxFc }
     */
    @Basic
    @Column(name = "tax_fc", scale = 2, precision = 14)
    public BigDecimal getTaxFc() {
        return taxFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxFc the value to set into {@link #taxFc}
     */
    public void setTaxFc(BigDecimal taxFc) {
        this.taxFc.set(taxFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #exportFc }
     */
    @Basic
    @Column(name = "export_fc", scale = 2, precision = 14)
    public BigDecimal getExportFc() {
        return exportFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param exportFc the value to set into {@link #exportFc}
     */
    public void setExportFc(BigDecimal exportFc) {
        this.exportFc.set(exportFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #discountFc }
     */
    @Basic
    @Column(name = "discount_fc", scale = 2, precision = 14)
    public BigDecimal getDiscountFc() {
        return discountFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param discountFc the value to set into {@link #discountFc}
     */
    public void setDiscountFc(BigDecimal discountFc) {
        this.discountFc.set(discountFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #discountTaxFc }
     */
    @Basic
    @Column(name = "discount_tax_fc", scale = 2, precision = 14)
    public BigDecimal getDiscountTaxFc() {
        return discountTaxFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param discountTaxFc the value to set into {@link #discountTaxFc}
     */
    public void setDiscountTaxFc(BigDecimal discountTaxFc) {
        this.discountTaxFc.set(discountTaxFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #exemptFc }
     */
    @Basic
    @Column(name = "exempt_fc", scale = 2, precision = 14)
    public BigDecimal getExemptFc() {
        return exemptFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param exemptFc the value to set into {@link #exemptFc}
     */
    public void setExemptFc(BigDecimal exemptFc) {
        this.exemptFc.set(exemptFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxFreeFc }
     */
    @Basic
    @Column(name = "tax_free_fc", scale = 2, precision = 14)
    public BigDecimal getTaxFreeFc() {
        return taxFreeFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxFreeFc the value to set into {@link #taxFreeFc}
     */
    public void setTaxFreeFc(BigDecimal taxFreeFc) {
        this.taxFreeFc.set(taxFreeFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #icbpFc }
     */
    @Basic
    @Column(name = "icbp_fc", scale = 2, precision = 14)
    public BigDecimal getIcbpFc() {
        return icbpFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param icbpFc the value to set into {@link #icbpFc}
     */
    public void setIcbpFc(BigDecimal icbpFc) {
        this.icbpFc.set(icbpFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #othersFc }
     */
    @Basic
    @Column(name = "others_fc", scale = 2, precision = 14)
    public BigDecimal getOthersFc() {
        return othersFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param othersFc the value to set into {@link #othersFc}
     */
    public void setOthersFc(BigDecimal othersFc) {
        this.othersFc.set(othersFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #payableFc }
     */
    @Basic
    @Column(name = "payable_fc", scale = 2, precision = 14)
    public BigDecimal getPayableFc() {
        return payableFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param payableFc the value to set into {@link #payableFc}
     */
    public void setPayableFc(BigDecimal payableFc) {
        this.payableFc.set(payableFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #briefing }
     */
    @Basic
    @Column(name = "briefing")
    public String getBriefing() {
        return briefing.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param briefing the value to set into {@link #briefing}
     */
    public void setBriefing(String briefing) {
        this.briefing.set(briefing);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #dim1 }
     */
    @Basic
    @Column(name = "dim1")
    public String getDim1() {
        return dim1.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param dim1 the value to set into {@link #dim1}
     */
    public void setDim1(String dim1) {
        this.dim1.set(dim1);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #dim2 }
     */
    @Basic
    @Column(name = "dim2")
    public String getDim2() {
        return dim2.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param dim2 the value to set into {@link #dim2}
     */
    public void setDim2(String dim2) {
        this.dim2.set(dim2);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #dim3 }
     */
    @Basic
    @Column(name = "dim3")
    public String getDim3() {
        return dim3.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param dim3 the value to set into {@link #dim3}
     */
    public void setDim3(String dim3) {
        this.dim3.set(dim3);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #dim4 }
     */
    @Basic
    @Column(name = "dim4")

    public String getDim4() {
        return dim4.get();
    }

    /**
     * Public accessor - setter
     * .
     * the value to set into {@link #dim4}
     */
    public void setDim4(String dim4) {
        this.dim4.set(dim4);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxId }
     */
    @Basic
    @Column(name = "tax_id")
    public String getTaxId() {
        return taxId.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxId the value to set into {@link #taxId}
     */
    public void setTaxId(String taxId) {
        this.taxId.set(taxId);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #owner }
     */
    @ManyToOne
    @JoinColumn(name = "owner", referencedColumnName = "id", nullable = false)
    public Folio getOwner() {
        return owner.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param owner the value to set into {@link #owner}
     */
    public void setOwner(Folio owner) {
        this.owner.set(owner);
    }
}
