/*
 *  Perutax - Taxation software for Peru.
 *     Copyright (C) 2021-2022  Ingenieria Informatica Yupay SACS
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.yupay.perutax.entities;

import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * This entity represents a total item
 * in the footer section of a folio document.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
@Entity
@Table(name = "folio_total", schema = "public")
public class FolioTotal {
    /**
     * The autogenerated ID.
     */
    private long id;
    /**
     * The type of this total item.
     */
    private FolioTotalType totalType;
    /**
     * The amount expressed in foreign currency.
     */
    private BigDecimal amountFc;
    /**
     * The amount expressed in system currency.
     */
    private BigDecimal amountSc;
    /**
     * The owner entity of this total.
     */
    private Folio owner;

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #id}
     */
    @GeneratedValue(generator = "sq_foliototal")
    @SequenceGenerator(name = "sq_foliototal",
            schema = "public",
            sequenceName = "sq_folio_total_id",
            allocationSize = 1)
    @Id
    @Column(name = "id")
    public long getId() {
        return id;
    }

    /**
     * Public accessor - setter.
     *
     * @param id value of {@link #id}
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #totalType}
     */
    @Basic
    @Column(name = "total_type")
    public FolioTotalType getTotalType() {
        return totalType;
    }

    /**
     * Public accessor - setter.
     *
     * @param totalType value of {@link #totalType}
     */
    public void setTotalType(FolioTotalType totalType) {
        this.totalType = totalType;
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #amountFc}
     */
    @Basic
    @Column(name = "amount_fc", scale = 2, precision = 14)
    public BigDecimal getAmountFc() {
        return amountFc;
    }

    /**
     * Public accessor - setter.
     *
     * @param amountFc value of {@link #amountFc}
     */
    public void setAmountFc(BigDecimal amountFc) {
        this.amountFc = amountFc;
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #amountSc}
     */
    @Basic
    @Column(name = "amount_sc", scale = 2, precision = 14)
    public BigDecimal getAmountSc() {
        return amountSc;
    }

    /**
     * Public accessor - setter.
     *
     * @param amountSc value of {@link #amountSc}
     */
    public void setAmountSc(BigDecimal amountSc) {
        this.amountSc = amountSc;
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #owner}
     */
    @ManyToOne
    @JoinColumn(name = "owner", referencedColumnName = "id", nullable = false)
    public Folio getOwner() {
        return owner;
    }

    /**
     * Public accessor - setter.
     *
     * @param owner value of {@link #owner}
     */
    public void setOwner(Folio owner) {
        this.owner = owner;
    }
}
