/*
 *  Perutax - Taxation software for Peru.
 *     Copyright (C) 2021-2022  Ingenieria Informatica Yupay SACS
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.yupay.perutax.entities;

import jakarta.persistence.*;
import javafx.beans.property.*;

import java.math.BigDecimal;

/**
 * This entity is a template for a folio line, so
 * the user will be able to choose it when registering
 * the folio, and will have prices, briefings and Taxation ID
 * of the items being added.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
@Entity
@Table(name = "folio_line_tmp", schema = "public")
public class FolioLineTemplate {
    /**
     * Autogenerated ID.
     */
    private final LongProperty id
            = new SimpleLongProperty(this, "id");
    /**
     * Unique title to identify the template.
     */
    private final StringProperty title
            = new SimpleStringProperty(this, "title");
    /**
     * The taxation ID of the item, assigned by UN.
     */
    private final StringProperty taxId
            = new SimpleStringProperty(this, "taxId");
    /**
     * Briefing text of the line.
     *
     * @implNote here only there's briefing
     * because the details (Dimensions) should be
     * specific of each sold item.
     */
    private final StringProperty briefing
            = new SimpleStringProperty(this, "briefing");
    /**
     * Taxable amount - folio currency.
     */
    private final ObjectProperty<BigDecimal> taxableFc
            = new SimpleObjectProperty<>(this, "taxableFc");
    /**
     * Tax amount - folio currency.
     */
    private final ObjectProperty<BigDecimal> taxFc
            = new SimpleObjectProperty<>(this, "taxFc");
    /**
     * Exportaiton value - folio currency.
     */
    private final ObjectProperty<BigDecimal> exportFc
            = new SimpleObjectProperty<>(this, "exportFc");
    /**
     * Discount amount (price portion) - folio currency.
     */
    private final ObjectProperty<BigDecimal> discountFc
            = new SimpleObjectProperty<>(this, "discountFc");
    /**
     * Discount amount (tax portion) - folio currency.
     */
    private final ObjectProperty<BigDecimal> discountTaxFc
            = new SimpleObjectProperty<>(this, "discountTaxFc");
    /**
     * Tax exempt amount.
     * Expressed in folio currency.
     *
     * @implNote The difference between a tax free
     * item and exempt amount, is that the tax free
     * item is an item not included in the taxation law
     * as a taxable amount; while an exempt amount is
     * the one that is included in law as a taxable item
     * but for some sepcial reason, has been
     * temporarily exempted from paying the tax.
     */
    private final ObjectProperty<BigDecimal> exemptFc
            = new SimpleObjectProperty<>(this, "exemptFc");
    /**
     * Tax free amount - folio currency.
     */
    private final ObjectProperty<BigDecimal> taxFreeFc
            = new SimpleObjectProperty<>(this, "taxFreeFc");
    /**
     * ICBP amount (bag plastic tax) - folio currency.
     */
    private final ObjectProperty<BigDecimal> icbpFc
            = new SimpleObjectProperty<>(this, "icbpFc");
    /**
     * Others amounts - folio currency.
     */
    private final ObjectProperty<BigDecimal> othersFc
            = new SimpleObjectProperty<>(this, "othersFc");
    /**
     * Total payable amount - folio currency.
     */
    private final ObjectProperty<BigDecimal> payableFc
            = new SimpleObjectProperty<>(this, "payableFc");
    /**
     * The currency in which the folio line template
     * is expressed.
     */
    private final ObjectProperty<Currenci> currency
            = new SimpleObjectProperty<>(this, "currency");

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #id }
     */
    @GeneratedValue(generator = "sq_folioline_tmp")
    @SequenceGenerator(name = "sq_folioline_tmp",
            schema = "public",
            sequenceName = "sq_folio_line_template",
            allocationSize = 1)
    @Id
    @Column(name = "id")
    public long getId() {
        return id.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param id value to set into {@link #id}
     */
    public void setId(long id) {
        this.id.set(id);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #title }
     */
    @Basic
    @Column(name = "title")
    public String getTitle() {
        return title.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param title value to set into {@link #title}
     */
    public void setTitle(String title) {
        this.title.set(title);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxId }
     */
    @Basic
    @Column(name = "tax_id")
    public String getTaxId() {
        return taxId.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxId value to set into {@link #taxId}
     */
    public void setTaxId(String taxId) {
        this.taxId.set(taxId);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #briefing }
     */
    @Basic
    @Column(name = "briefing")
    public String getBriefing() {
        return briefing.get();
    }

    public void setBriefing(String briefing) {
        this.briefing.set(briefing);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxableFc }
     */
    @Basic
    @Column(name = "taxable_fc", scale = 2, precision = 14)
    public BigDecimal getTaxableFc() {
        return taxableFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxableFc value to set into {@link #taxableFc}
     */
    public void setTaxableFc(BigDecimal taxableFc) {
        this.taxableFc.set(taxableFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxFc }
     */
    @Basic
    @Column(name = "tax_fc", scale = 2, precision = 14)
    public BigDecimal getTaxFc() {
        return taxFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxFc value to set into {@link #taxFc}
     */
    public void setTaxFc(BigDecimal taxFc) {
        this.taxFc.set(taxFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #exportFc }
     */
    @Basic
    @Column(name = "export_fc", scale = 2, precision = 14)
    public BigDecimal getExportFc() {
        return exportFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param exportFc value to set into {@link #exportFc}
     */
    public void setExportFc(BigDecimal exportFc) {
        this.exportFc.set(exportFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #discountFc }
     */
    @Basic
    @Column(name = "discount_fc", scale = 2, precision = 14)
    public BigDecimal getDiscountFc() {
        return discountFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param discountFc value to set into {@link #discountFc}
     */
    public void setDiscountFc(BigDecimal discountFc) {
        this.discountFc.set(discountFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #discountTaxFc }
     */
    @Basic
    @Column(name = "discount_tax_fc", scale = 2, precision = 14)
    public BigDecimal getDiscountTaxFc() {
        return discountTaxFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param discountTaxFc value to set into {@link #discountTaxFc}
     */
    public void setDiscountTaxFc(BigDecimal discountTaxFc) {
        this.discountTaxFc.set(discountTaxFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #exemptFc }
     */
    @Basic
    @Column(name = "exempt_fc", scale = 2, precision = 14)
    public BigDecimal getExemptFc() {
        return exemptFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param exemptFc value to set into {@link #exemptFc}
     */
    public void setExemptFc(BigDecimal exemptFc) {
        this.exemptFc.set(exemptFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxFreeFc }
     */
    @Basic
    @Column(name = "tax_free_fc", scale = 2, precision = 14)
    public BigDecimal getTaxFreeFc() {
        return taxFreeFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxFreeFc value to set into {@link #taxFreeFc}
     */
    public void setTaxFreeFc(BigDecimal taxFreeFc) {
        this.taxFreeFc.set(taxFreeFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #icbpFc }
     */
    @Basic
    @Column(name = "icbp_fc", scale = 2, precision = 14)
    public BigDecimal getIcbpFc() {
        return icbpFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param icbpFc value to set into {@link #icbpFc}
     */
    public void setIcbpFc(BigDecimal icbpFc) {
        this.icbpFc.set(icbpFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #othersFc }
     */
    @Basic
    @Column(name = "others_fc", scale = 2, precision = 14)
    public BigDecimal getOthersFc() {
        return othersFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param othersFc value to set into {@link #othersFc}
     */
    public void setOthersFc(BigDecimal othersFc) {
        this.othersFc.set(othersFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #payableFc }
     */
    @Basic
    @Column(name = "payable_fc", scale = 2, precision = 14)
    public BigDecimal getPayableFc() {
        return payableFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param payableFc value to set into {@link #payableFc}
     */
    public void setPayableFc(BigDecimal payableFc) {
        this.payableFc.set(payableFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #currency }
     */
    @Basic
    @Column(name = "currency")
    public Currenci getCurrency() {
        return currency.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param currency value to set into {@link #currency}
     */
    public void setCurrency(Currenci currency) {
        this.currency.set(currency);
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #id}
     */
    public LongProperty idProperty() {
        return id;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #title}
     */
    public StringProperty titleProperty() {
        return title;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #taxId}
     */
    public StringProperty taxIdProperty() {
        return taxId;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #briefing}
     */
    public StringProperty briefingProperty() {
        return briefing;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #taxableFc}
     */
    public ObjectProperty<BigDecimal> taxableFcProperty() {
        return taxableFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #taxFc}
     */
    public ObjectProperty<BigDecimal> taxFcProperty() {
        return taxFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #exportFc}
     */
    public ObjectProperty<BigDecimal> exportFcProperty() {
        return exportFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #discountFc}
     */
    public ObjectProperty<BigDecimal> discountFcProperty() {
        return discountFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #discountTaxFc}
     */
    public ObjectProperty<BigDecimal> discountTaxFcProperty() {
        return discountTaxFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #exemptFc}
     */
    public ObjectProperty<BigDecimal> exemptFcProperty() {
        return exemptFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #taxFreeFc}
     */
    public ObjectProperty<BigDecimal> taxFreeFcProperty() {
        return taxFreeFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #icbpFc}
     */
    public ObjectProperty<BigDecimal> icbpFcProperty() {
        return icbpFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #othersFc}
     */
    public ObjectProperty<BigDecimal> othersFcProperty() {
        return othersFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #payableFc}
     */
    public ObjectProperty<BigDecimal> payableFcProperty() {
        return payableFc;
    }

    /**
     * JavaFX accessor - property.
     * @return property {@link #currency}
     */
    public ObjectProperty<Currenci> currencyProperty() {
        return currency;
    }
}
