/*
 *  Perutax - Taxation software for Peru.
 *     Copyright (C) 2021-2022  Ingenieria Informatica Yupay SACS
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.yupay.perutax.entities;

import jakarta.persistence.*;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

import java.math.BigDecimal;

/**
 * This entity represents a total item
 * in the footer section of a folio document.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
@Entity
@Table(name = "folio_total", schema = "public")
public class FolioTotal {
    /**
     * The autogenerated ID.
     */
    private final LongProperty id =
            new SimpleLongProperty(this, "id");
    /**
     * The type of this total item.
     */
    private final ObjectProperty<FolioTotalType> totalType =
            new SimpleObjectProperty<>(this, "totalType");
    /**
     * The amount expressed in foreign currency.
     */
    private final ObjectProperty<BigDecimal> amountFc =
            new SimpleObjectProperty<>(this, "amountFc");
    /**
     * The amount expressed in system currency.
     */
    private final ObjectProperty<BigDecimal> amountSc =
            new SimpleObjectProperty<>(this, "amountSc");
    /**
     * The owner entity of this total.
     */
    private final ObjectProperty<Folio> owner =
            new SimpleObjectProperty<>(this, "owner");

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #id}
     */
    @GeneratedValue(generator = "sq_foliototal")
    @SequenceGenerator(name = "sq_foliototal",
            schema = "public",
            sequenceName = "sq_folio_total_id",
            allocationSize = 1)
    @Id
    @Column(name = "id")
    public long getId() {
        return id.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param id value of {@link #id}
     */
    public void setId(long id) {
        this.id.set(id);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #totalType}
     */
    @Basic
    @Column(name = "total_type")
    public FolioTotalType getTotalType() {
        return totalType.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param totalType value of {@link #totalType}
     */
    public void setTotalType(FolioTotalType totalType) {
        this.totalType.set(totalType);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #amountFc}
     */
    @Basic
    @Column(name = "amount_fc", scale = 2, precision = 14)
    public BigDecimal getAmountFc() {
        return amountFc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param amountFc value of {@link #amountFc}
     */
    public void setAmountFc(BigDecimal amountFc) {
        this.amountFc.set(amountFc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #amountSc}
     */
    @Basic
    @Column(name = "amount_sc", scale = 2, precision = 14)
    public BigDecimal getAmountSc() {
        return amountSc.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param amountSc value of {@link #amountSc}
     */
    public void setAmountSc(BigDecimal amountSc) {
        this.amountSc.set(amountSc);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link  #owner}
     */
    @ManyToOne
    @JoinColumn(name = "owner", referencedColumnName = "id", nullable = false)
    public Folio getOwner() {
        return owner.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param owner value of {@link #owner}
     */
    public void setOwner(Folio owner) {
        this.owner.set(owner);
    }

    /**
     * JavaFX accessor - property.
     *
     * @return property {@link #id}
     */
    public LongProperty idProperty() {
        return id;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return property {@link #totalType}
     */
    public ObjectProperty<FolioTotalType> totalTypeProperty() {
        return totalType;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return property {@link #amountFc}
     */
    public ObjectProperty<BigDecimal> amountFcProperty() {
        return amountFc;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return property {@link #amountSc}
     */
    public ObjectProperty<BigDecimal> amountScProperty() {
        return amountSc;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return property {@link #owner}
     */
    public ObjectProperty<Folio> ownerProperty() {
        return owner;
    }
}
