/*
 *  Perutax - Taxation software for Peru.
 *     Copyright (C) 2021-2022  Ingenieria Informatica Yupay SACS
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.yupay.perutax.entities;

import jakarta.persistence.*;
import javafx.beans.property.*;
import org.eclipse.persistence.annotations.UuidGenerator;
import org.jetbrains.annotations.NotNull;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * This entity represents a sale scheme. A sale scheme
 * is used to compute the amounts when registering a
 * sale or product.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
@Entity
@Table(name = "sale_scheme", schema = "public")
public class SaleScheme {
    /**
     * The autogenerated ID.
     */
    private final StringProperty id =
            new SimpleStringProperty(this, "id");
    /**
     * Title of the scheme, a brief and friendly title.
     */
    private final StringProperty title =
            new SimpleStringProperty(this, "title");
    /**
     * Tax rate. It's overriden by the taxFee. This is the
     * rate that must be applied in order to compute the tax
     * when this scheme is used. Ie: 0.18 would be a tax of 18%
     */
    private final ObjectProperty<BigDecimal> taxRate =
            new SimpleObjectProperty<>(this, "taxRate");
    /**
     * Tax fee. If set, the taxRate should be ignored.
     * This is used to state that the tax in a sale scheme
     * is a fixed number (ie: a tax of 0.10¢)
     */
    private final ObjectProperty<BigDecimal> taxFee =
            new SimpleObjectProperty<>(this, "taxFee");
    /**
     * Class of the price/amount.
     */
    private final ObjectProperty<SaleTotalClass> amountClass =
            new SimpleObjectProperty<>(this, "amountClass");
    /**
     * Class of the tax amount.
     */
    private final ObjectProperty<SaleTotalClass> taxClass =
            new SimpleObjectProperty<>(this, "taxClass");
    /**
     * Trash flag, if true the sale scheme has been deprecated.
     */
    private final BooleanProperty trash =
            new SimpleBooleanProperty(this, "trash");
    /**
     * The factoring ID is the ID used in UBL2.0 to detect
     * that this scheme has been used.
     */
    private final StringProperty factoringId =
            new SimpleStringProperty(this, "factoringId");

    /**
     * Default constructor (JPA use).
     */
    public SaleScheme() {
    }

    /**
     * Copy constructor that takes all
     * fields values from another instance.
     *
     * @param another the another (source) instance.
     */
    public SaleScheme(@NotNull SaleScheme another) {
        setAmountClass(another.getAmountClass());
        setFactoringId(another.getFactoringId());
        setId(another.getId());
        setTaxClass(another.getTaxClass());
        setTaxFee(another.getTaxFee());
        setTaxRate(another.getTaxRate());
        setTitle(another.getTitle());
        setTrash(another.isTrash());
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #id}
     */
    @GeneratedValue(generator = "uuid_salescheme")
    @UuidGenerator(name = "uuid_salescheme")
    @Id
    @Column(name = "id", nullable = false, length = 36)
    public String getId() {
        return id.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param id value to set into {@link #id}
     */
    public void setId(String id) {
        this.id.set(id);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #title}
     */
    @Basic
    @Column(name = "title", nullable = false, length = -1)
    public String getTitle() {
        return title.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param title value to set into {@link #title}
     */
    public void setTitle(String title) {
        this.title.set(title);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxRate}
     */
    @Basic
    @Column(name = "tax_rate", precision = 5, scale = 4)
    public BigDecimal getTaxRate() {
        return taxRate.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxRate value to set into {@link #taxRate}
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate.set(taxRate);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxFee}
     */
    @Basic
    @Column(name = "tax_fee", precision = 14, scale = 2)
    public BigDecimal getTaxFee() {
        return taxFee.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxFee value to set into {@link #taxFee}
     */
    public void setTaxFee(BigDecimal taxFee) {
        this.taxFee.set(taxFee);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #amountClass}
     */
    @Basic
    @Enumerated(EnumType.STRING)
    @Column(name = "amount_class", nullable = false)
    public SaleTotalClass getAmountClass() {
        return amountClass.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param amountClass value to set into {@link #amountClass}
     */
    public void setAmountClass(SaleTotalClass amountClass) {
        this.amountClass.set(amountClass);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #taxClass}
     */
    @Basic
    @Enumerated(EnumType.STRING)
    @Column(name = "tax_class", nullable = false)
    public SaleTotalClass getTaxClass() {
        return taxClass.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param taxClass value to set into {@link #taxClass}
     */
    public void setTaxClass(SaleTotalClass taxClass) {
        this.taxClass.set(taxClass);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #trash}
     */
    @Basic
    @Column(name = "trash", nullable = false)
    public boolean isTrash() {
        return trash.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param trash value to set into {@link #trash}
     */
    public void setTrash(boolean trash) {
        this.trash.set(trash);
    }

    /**
     * Public accessor - getter.
     *
     * @return value of {@link #factoringId}
     */
    @Basic
    @Column(name = "factoring_id", nullable = false, length = -1)
    public String getFactoringId() {
        return factoringId.get();
    }

    /**
     * Public accessor - setter.
     *
     * @param factoringId value to set into {@link #factoringId}
     */
    public void setFactoringId(String factoringId) {
        this.factoringId.set(factoringId);
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #id}
     */
    public StringProperty idProperty() {
        return id;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #title}
     */
    public StringProperty titleProperty() {
        return title;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #taxRate}
     */
    public ObjectProperty<BigDecimal> taxRateProperty() {
        return taxRate;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #taxFee}
     */
    public ObjectProperty<BigDecimal> taxFeeProperty() {
        return taxFee;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #amountClass}
     */
    public ObjectProperty<SaleTotalClass> amountClassProperty() {
        return amountClass;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #taxClass}
     */
    public ObjectProperty<SaleTotalClass> taxClassProperty() {
        return taxClass;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #trash}
     */
    public BooleanProperty trashProperty() {
        return trash;
    }

    /**
     * JavaFX accessor - property.
     *
     * @return the property {@link #factoringId}
     */
    public StringProperty factoringIdProperty() {
        return factoringId;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof SaleScheme that &&
                Objects.equals(getId(), that.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
